trigger:
- none

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: TerraformInstaller@0
  inputs:
    terraformVersion: 'latest'

- script: terraform init
  displayName: 'Terraform Init'

- script: terraform destroy -auto-approve
  displayName: 'Terraform Destroy'
